name: Compressed Size

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fungible-systems/compressed-size-action@v2.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
